import { useState } from "react";
import "./TeachingPracticesDeck.css";

// All 54 cards, carried over verbatim from the original deck.
const CARDS = [
      {
        id: 1,
        title: "Retrieval Practice - Foundational",
        subtitle: "Testing strengthens memory",
        category: "blue",
        categoryLabel: "Learning & Memory",
        why: "Testing and retrieval strengthen memory more powerfully than restudying. Students remember what they retrieve—not what they reread.",
        tryThis: "Start class with 3–5 questions on previous week's material (unannounced, no grades). Call on students, discuss answers.",
        variation: "Use Quizizz, exit tickets, index cards, or cold calling. Any retrieval counts.",
        insight: "Don't use retrieval for brand-new material. Use it for old material → frees cognitive load for new concepts.",
        works: "All subjects, all levels",
        research: "Dunlosky et al. (2013); Roediger & Butler (2011)"
      },
      { id: 2, title: "Low-Stakes Quizzing", subtitle: "Frequent, ungraded retrieval", category: "blue", categoryLabel: "Learning & Memory", why: "Low-stakes quizzes harness retrieval practice without triggering test anxiety. Students retrieve knowledge frequently without high-stakes pressure.", tryThis: "Create 4–5 quick-check questions. Administer without grades (for practice only). Discuss answers.", variation: "Daily quizzes, weekly quizzes, Kahoot/Quizizz, handwritten index cards.", insight: "The benefit comes from retrieval, not grading. Removing stakes removes anxiety but keeps learning gains.", works: "All subjects, all levels", research: "Aronson et al. (2002); Roediger & Butler (2011)" },
      { id: 3, title: "Retrieval + Prior Knowledge", subtitle: "Activate existing knowledge first", category: "blue", categoryLabel: "Learning & Memory", why: "Retrieval is most powerful when students activate existing knowledge before new learning. This creates hooks for elaboration.", tryThis: "Before teaching: 'What do you already know about X?' Spend 5 min retrieving prior knowledge. *Then* introduce new concepts.", variation: "KWL charts, pre-quizzes on foundational knowledge, peer-taught retrieval, concept maps of prior learning.", insight: "You can't retrieve knowledge students don't have. Activate what exists first; build what's missing before new learning.", works: "All subjects", research: "Anderson (1984); Rosenshine (1997)" },
      { id: 4, title: "Retrieval + Transfer Tasks", subtitle: "Apply retrieved knowledge to new contexts", category: "blue", categoryLabel: "Learning & Memory", why: "When students retrieve knowledge and apply it to novel problems (transfer tasks), they develop true understanding and prevent surface-level memorization.", tryThis: "End a lesson with a task that looks *different* from practice problems but uses the same concept.", variation: "Near transfer, far transfer, cross-discipline applications, real-world problem solving.", insight: "Transfer is harder than retrieval. It's a better indicator of real learning.", works: "All subjects", research: "Bjork & Bjork (1992); Haskell (2001)" },
      { id: 6, title: "Retrieval Practice Scheduling", subtitle: "When to retrieve matters", category: "blue", categoryLabel: "Learning & Memory", why: "Retrieving material after it's partially forgotten strengthens memory most. Timing of retrieval is critical.", tryThis: "Design retrieval at three timepoints: (1) Same lesson/next day, (2) 1–2 weeks later, (3) End of unit.", variation: "Optimal gap theory scheduling, graduated difficulty increases, progressive retrieval challenges.", insight: "Retrieval is most powerful when material has been partially forgotten. Balance is key.", works: "All subjects, especially skill-building", research: "Bjork & Bjork (1992); Cepeda et al. (2006)" },
      { id: 7, title: "Retrieval + Metacognition", subtitle: "Combine retrieval with confidence monitoring", category: "blue", categoryLabel: "Learning & Memory", why: "When students retrieve AND monitor their confidence, they develop accurate self-awareness about what they actually know.", tryThis: "After a retrieval task, add: 'Rate your confidence: 1–5 (completely unsure to completely sure).' Compare confidence to accuracy.", variation: "Confidence ratings before/after retrieval, error detection during retrieval, accuracy monitoring.", insight: "Many students confuse fluency (feels familiar) with mastery (can retrieve it). Metacognition exposes this gap.", works: "All subjects", research: "Schraw & Dennison (1994); Dunlosky et al. (2013)" },
      { id: 8, title: "Retrieval + Immediate Feedback", subtitle: "Retrieval is more effective with fast feedback", category: "blue", categoryLabel: "Learning & Memory", why: "Retrieval alone strengthens memory. When paired with immediate, specific feedback, the effect is even stronger.", tryThis: "During or right after retrieval practice, provide immediate feedback. Don't wait until the next day.", variation: "Self-grading with answer keys, peer-checking, technology with instant feedback, teacher discussion immediately after.", insight: "Delayed feedback is still useful, but immediate feedback prevents errors from being practiced/reinforced.", works: "All subjects, all levels", research: "Metcalfe (2017); Roediger & Butler (2011)" },
      { id: 9, title: "Spacing - Foundational", subtitle: "Distributed practice over time", category: "teal", categoryLabel: "Spacing", why: "Spacing produces stronger, more durable memory than massed practice. Students forget slightly between sessions, requiring effort to relearn—that effort strengthens memory.", tryThis: "Pick a unit from 3–4 weeks ago. Design 3 brief retrieval moments this week: Mon: 2 problems • Wed: 1 problem • Fri: Quiz.", variation: "Weekly review problems, spiral curricula, cumulative assessments, rotating warm-ups.", insight: "'Friday review' doesn't work (massed). Spaced retrieval across the week does.", works: "All subjects, all levels", research: "Cepeda et al. (2006); Dunlosky et al. (2013)" },
      { id: 10, title: "Optimal Spacing Intervals", subtitle: "How far apart should reviews be?", category: "teal", categoryLabel: "Spacing", why: "Research shows optimal spacing intervals are roughly 10–20% of the retention interval.", tryThis: "Plan a unit. Estimate when you want students to remember it best. Space reviews backward from that deadline, roughly every 2–3 weeks.", variation: "Leitner scheduling, Anki spacing algorithm, teacher-designed spacing calendar, spiral curriculum pacing.", insight: "Too close = no benefit. Too far = too much forgetting. 10–20% of retention interval is the sweet spot.", works: "All subjects, especially factual content and vocabulary", research: "Cepeda et al. (2006); Dunlosky et al. (2013)" },
      { id: 11, title: "Spaced Review Protocols", subtitle: "Systematic spacing built into curriculum", category: "teal", categoryLabel: "Spacing", why: "Systematic protocols create predictable spacing and ensure nothing is forgotten.", tryThis: "Design a 4-week spiral: Week 1 (teach), Week 2 (review once), Week 3 (review again), Week 4 (quiz). Build into your pacing calendar.", variation: "Cornell notes with spaced review cues, Leitner system, digital spacing apps, spaced practice worksheets.", insight: "Spacing should be planned, not reactive. Build it into curriculum design from the start.", works: "All subjects", research: "Cepeda et al. (2006); Roediger & Butler (2011)" },
      { id: 12, title: "Spacing + Retrieval (Spaced Retrieval)", subtitle: "The most powerful combination", category: "teal", categoryLabel: "Spacing", why: "Spaced retrieval is the most powerful learning strategy. It combines spacing's forgetting/relearning effect with retrieval's memory-strengthening effect.", tryThis: "Every homework: Mix in problems from old units (spaced). Every quiz: Include old material. Every test: Cumulative.", variation: "Cumulative assessments, spiral problem sets, rolling homework, weekly review blocks.", insight: "This combination beats all other study strategies by a wide margin. It should be your default.", works: "All subjects, all levels", research: "Dunlosky et al. (2013); Roediger & Butler (2011)" },
      { id: 13, title: "Spacing Across the Year", subtitle: "Revisit content repeatedly throughout the year", category: "teal", categoryLabel: "Spacing", why: "When content is revisited multiple times throughout the year, memory persists. Single exposures lead to forgetting.", tryThis: "Identify 5–10 essential concepts that should be remembered all year. Schedule them reviewed at least 4 times across the year.", variation: "Spiraling curriculum, rolling vocabulary reviews, ongoing concept reinforcement, distributed practice blocks.", insight: "This requires curriculum planning. Build spacing into the design of your course.", works: "All subjects, especially foundational skills", research: "Cepeda et al. (2006); Rosenshine (1997)" },
      { id: 14, title: "Spacing + Cognitive Load", subtitle: "Spacing reduces reteaching needs", category: "teal", categoryLabel: "Spacing", why: "Without spacing, students forget and you must reteach. With spacing, you spend less time reteaching, freeing cognitive load for new learning.", tryThis: "Review your curriculum. How much time do you spend reteaching? Space that content earlier, and reteaching time decreases.", variation: "Maintenance schedules, spiral review, cumulative practice, distributed practice throughout units.", insight: "Spacing requires planning but saves instructional time by reducing reteaching needs.", works: "All subjects, all levels", research: "Dunlosky et al. (2013); Sweller (1988)" },
      { id: 15, title: "Spacing + Interleaving", subtitle: "Mix old content with new (the spiral)", category: "teal", categoryLabel: "Spacing", why: "When spacing meets interleaving—old content mixed into current assignments—students maintain old knowledge while learning new things.", tryThis: "Homework this week: 70% new material (this week's lesson), 30% old material (from previous units, mixed in).", variation: "Spiral problem sets, mixed reviews, cumulative worksheets, integrated spiral reviews.", insight: "This is the most efficient use of class time: learning new AND maintaining old through the same practice.", works: "All subjects, especially mathematics and skill-based", research: "Dunlosky et al. (2013); Rohrer & Taylor (2007)" },
      { id: 16, title: "Interleaving - Foundational", subtitle: "Mixed practice (don't block)", category: "purple", categoryLabel: "Interleaving", why: "Mixing different problem types during practice is harder in the moment but builds better learning. Students learn to recognize which strategy fits which problem.", tryThis: "Homework this week: Mix problem types from multiple lessons. Include 1–2 from previous lessons too.", variation: "Randomize problem order, use mixed practice sets, spiral assessments.", insight: "Blocked practice feels fluent but students plateau. Interleaving is harder but transfer is stronger.", works: "Math, sciences, languages, skill-building", research: "Rohrer & Taylor (2007); Dunlosky et al. (2013)" },
      { id: 17, title: "Interleaving + Problem Recognition", subtitle: "Learn to categorize problems", category: "purple", categoryLabel: "Interleaving", why: "Blocked practice teaches HOW to solve a type. Interleaved practice teaches students to RECOGNIZE which type of problem they're facing.", tryThis: "Assignment design: Mix problems from different chapters/units. Don't label them ('Here are 5 quadratics, 5 linears'). Make students figure out which strategy applies.", variation: "Unlabeled problem sets, category-mixing exercises, real-world applications (unlabeled), cumulative review.", insight: "Students often solve correctly in homework (blocked) but fail on tests (mixed). Interleaving closes that gap.", works: "Math, sciences, procedural skills", research: "Rohrer & Taylor (2007); Paas & van Merriënboer (2020)" },
      { id: 18, title: "Interleaving + Transfer", subtitle: "Mix practice to improve transfer", category: "purple", categoryLabel: "Interleaving", why: "Transfer depends on recognizing which strategy/principle applies. Interleaving forces this recognition, so transfer improves dramatically.", tryThis: "After a unit, give problems that LOOK different but use the same concepts. Mix in problems from previous units (spacing + interleaving).", variation: "Near-far transfer tasks, cross-context applications, unmarked problem sets, challenge problems.", insight: "Students who practice only blocked problems often can't transfer. Interleaving builds the discrimination needed.", works: "All subjects, especially complex problem-solving", research: "Rohrer & Taylor (2007); Bjork & Bjork (1992)" },
      { id: 19, title: "Interleaving Homework Design", subtitle: "Structuring assignments for mixed practice", category: "purple", categoryLabel: "Interleaving", why: "Intentional homework design that interleaves problems is the easiest way to implement this. It requires deliberate assignment construction.", tryThis: "Next homework: Redesign so 60% is new material and 40% is old material (previous units), mixed throughout (not separate sections).", variation: "Random shuffling, alternating problem types, ratio-based mixing, cumulative problem banks.", insight: "Interleaving requires intentional design. If you just give 'all Chapter 5 problems,' you're blocking.", works: "All subjects with practice components", research: "Rohrer & Taylor (2007); Dunlosky et al. (2013)" },
      { id: 20, title: "Interleaving + Confidence", subtitle: "When interleaving feels hard, learning is happening", category: "purple", categoryLabel: "Interleaving", why: "Interleaved practice FEELS harder than blocked practice. This difficulty is a SIGN of learning, not failure.", tryThis: "Tell students: 'This homework feels harder because you're mixing problems. That's good—it means real learning. Blocked problems feel easy but don't stick.'", variation: "Pre-explaining the difficulty, normalizing struggle, metacognitive reflections on difficulty as learning signal.", insight: "If students think difficulty = bad learning, they'll reject interleaving. Reframe: difficulty during practice = deep learning.", works: "All subjects", research: "Bjork & Bjork (1992); Dunlosky et al. (2013)" },
      { id: 21, title: "Interleaving + Feedback", subtitle: "Feedback on mixed problems must address strategy selection", category: "purple", categoryLabel: "Interleaving", why: "Feedback on interleaved problems should highlight not just right/wrong, but WHICH STRATEGY was needed.", tryThis: "On interleaved homework, provide feedback: 'This was a quadratic problem (notice x² term). Try factoring first next time.'", variation: "Strategy-focused feedback, problem-type identification feedback, metacognitive feedback about strategy selection.", insight: "'Wrong' feedback is less helpful than 'This required Strategy X—here's how to recognize that next time.'", works: "Problem-solving subjects", research: "Rohrer & Taylor (2007); Metcalfe (2017)" },
      { id: 23, title: "Metacognition - Foundational", subtitle: "Self-monitoring & strategy adjustment", category: "green", categoryLabel: "Metacognition", why: "Metacognition is awareness of your own thinking. Students who monitor understanding and adjust strategies learn better. This is a learnable skill.", tryThis: "After students work on a problem, ask: 'Rate your confidence: 1–5' • 'What strategy did you use?' • 'Would you use it again?'", variation: "Think-alouds, reflection prompts, strategy instruction, peer explanations.", insight: "Make the THINKING PROCESS as explicit as the answer. Teach strategies.", works: "All subjects", research: "Schraw & Dennison (1994); Efklides (2008)" },
      { id: 24, title: "Confidence Ratings & Calibration", subtitle: "Help students know what they actually know", category: "green", categoryLabel: "Metacognition", why: "Students confuse fluency (feels familiar) with mastery (can retrieve it). Confidence ratings expose this gap. Calibration improves with practice.", tryThis: "After retrieval: 'Rate confidence 1–5.' Later, compare to actual score. 'Were you right about what you know?'", variation: "Confidence before/after studying, accuracy vs. confidence graphs, calibration exercises, pre-test confidence vs. post-test accuracy.", insight: "Calibration improves with practice. Regular confidence ratings help students develop accurate self-assessment.", works: "All subjects", research: "Schraw & Dennison (1994); Dunlosky et al. (2013)" },
      { id: 25, title: "Think-Alouds", subtitle: "Narrate your thinking (and theirs)", category: "green", categoryLabel: "Metacognition", why: "When you verbalize thinking while solving, students see the PROCESS they usually can't see. They learn thinking is messy, iterative, self-correcting.", tryThis: "Solve a problem in front of class while narrating: 'First I'll look for... then I notice... now I'm stuck, so I'll... ah, that worked.'", variation: "Student think-alouds, peer think-alouds, video think-alouds.", insight: "Think-alouds demystify expertise. Students realize experts also get stuck and adjust.", works: "All subjects", research: "Schoenfeld (1985); Pressley & Afflerbach (1995)" },
      { id: 26, title: "Strategy Instruction & Selection", subtitle: "Teach HOW to choose strategies", category: "green", categoryLabel: "Metacognition", why: "Students don't automatically know when to use different strategies. Explicit instruction on WHEN and HOW to use strategies accelerates learning.", tryThis: "Pick one cognitive strategy. Break into 3–5 steps. Model it aloud. Have students practice with support.", variation: "Anchor charts, strategy posters, guided practice, fading support over time, metacognitive strategy selection.", insight: "Students need BOTH knowledge AND strategies. And they need to know WHEN to use each strategy.", works: "All subjects", research: "Rosenshine (1997); Pressley & Afflerbach (1995)" },
      { id: 27, title: "Error Detection & Self-Correction", subtitle: "Help students catch and fix their own errors", category: "green", categoryLabel: "Metacognition", why: "Students who notice errors and self-correct learn more than those who make errors and never realize.", tryThis: "When students make errors, pause: 'Does this look right? Check your work. What's the mistake?' Let them find and fix it.", variation: "Self-checking protocols, accuracy monitoring, error detection practice, peer error detection, checklist-based self-checking.", insight: "Self-correction is more powerful than teacher correction. It builds metacognitive awareness and ownership.", works: "All subjects", research: "Metcalfe (2017); Bjork & Bjork (1992)" },
      { id: 28, title: "Reflection & Learning Journals", subtitle: "Students reflect on their learning process", category: "green", categoryLabel: "Metacognition", why: "Regular reflection on HOW students learned (not just what) builds metacognitive awareness.", tryThis: "Weekly: 'What did you learn? How did you learn it? What was hard? What strategy helped?'", variation: "Learning journals, reflection prompts, exit tickets, end-of-unit reflections, video reflections.", insight: "Reflection works best with SPECIFIC PROMPTS (not just 'how do you feel?'). Ask about thinking processes and strategies.", works: "All subjects", research: "Schon (1983); Brookfield & Preskill (2005)" },
      { id: 29, title: "Goal-Setting & Progress Monitoring", subtitle: "Students track their own learning", category: "green", categoryLabel: "Metacognition", why: "When students set goals (with guidance) and monitor progress, they develop ownership and metacognitive awareness.", tryThis: "Help students set 1–2 specific, measurable goals for the week/unit. Check in mid-way. Celebrate progress.", variation: "SMART goals, student-created goals, progress charts, rubric-based tracking, conference-based goal-setting.", insight: "Goals work best when students OWN them (vs. teacher-imposed). Support them in setting realistic, stretching goals.", works: "All subjects, all levels", research: "Locke & Latham (2002); Ryan & Deci (2000)" },
      { id: 30, title: "Metacognitive Strategy Use with Interleaving", subtitle: "Metacognition makes interleaving more effective", category: "green", categoryLabel: "Metacognition", why: "When students reflect on WHICH STRATEGY they're using with interleaved problems, they improve at recognizing/discriminating between problems.", tryThis: "With interleaved practice: 'Label what type of problem this is. Explain which strategy you used. Would you use that strategy again?'", variation: "Strategy labels during interleaved practice, metacognitive reflection on problem types, peer discussion of strategy choices.", insight: "Metacognition + Interleaving = especially powerful. Students develop both procedural skill AND conceptual understanding.", works: "Problem-solving subjects", research: "Rohrer & Taylor (2007); Schraw & Dennison (1994)" },
      { id: 31, title: "Feedback - Foundational", subtitle: "Information about performance", category: "amber", categoryLabel: "Feedback", why: "Specific, timely feedback about errors helps students correct misconceptions and adjust strategies. Generic praise doesn't improve learning.", tryThis: "On today's assignment, provide SPECIFIC feedback on 2–3 misconceptions: 'You used the right formula, but misread the exponent. Check line 2.'", variation: "Written feedback, oral feedback, video feedback, peer feedback, self-assessment feedback, rubric-based feedback.", insight: "Feedback is most effective when students can ACT on it soon (not after unit ends). Timing and specificity matter.", works: "All subjects", research: "Hattie & Timperley (2007); Wiggins (1998)" },
      { id: 33, title: "Feedback + Retrieval Practice", subtitle: "Feedback after retrieval attempts is most powerful", category: "amber", categoryLabel: "Feedback", why: "Feedback is most powerful when given right after a retrieval attempt (quiz, problem, assignment). Students are actively engaged.", tryThis: "During or right after retrieval practice, provide immediate feedback. Don't wait until the next day.", variation: "Self-grading with answer keys, peer-checking, technology with instant feedback, teacher discussion immediately after.", insight: "Delayed feedback is less effective. Front-load feedback when students are most receptive.", works: "All subjects, all levels", research: "Metcalfe (2017); Roediger & Butler (2011)" },
      { id: 34, title: "Feedback on Metacognition", subtitle: "Help students think better about their thinking", category: "amber", categoryLabel: "Feedback", why: "Feedback addressing THINKING PROCESSES (strategies, confidence, effort) builds metacognition. Feedback on answers alone doesn't.", tryThis: "Feedback should include: 'What you did right, where you got stuck, what strategy would have helped, how to recognize this problem type.'", variation: "Process-focused feedback, strategy-focused feedback, metacognitive feedback, error pattern feedback.", insight: "Metacognitive feedback is often missing. Add it to build both skills and self-awareness.", works: "All subjects", research: "Schraw & Dennison (1994); Hattie & Timperley (2007)" },
      { id: 35, title: "Peer Feedback", subtitle: "Students review each other's work", category: "amber", categoryLabel: "Feedback", why: "Giving feedback to peers deepens understanding (reviewers learn). Receiving peer feedback is less threatening than teacher feedback.", tryThis: "Peer review: Pair students. Give rubric or feedback frame ('I noticed... I wondered... You could...'). Have them swap and comment.", variation: "Peer editing, peer grading with rubrics, structured feedback protocols, gallery walks, document review.", insight: "Peer feedback works best with STRUCTURE (rubrics, sentence stems, exemplars). Unstructured peer review is often vague.", works: "Writing, projects, presentations, problem-solving", research: "Nicol et al. (2014); Sadler (1989)" },
      { id: 36, title: "Self-Assessment & Self-Feedback", subtitle: "Students evaluate and adjust their own work", category: "amber", categoryLabel: "Feedback", why: "When students assess themselves against clear criteria, they develop metacognitive awareness and ownership.", tryThis: "After assignment: Students rate 'Not yet (1) to Proficient (4)' on 2–3 criteria. Then ask: 'What's missing? What would improve this?'", variation: "Rubric-based self-evaluation, confidence ratings, reflection prompts, revision checklists, peer-assisted self-assessment.", insight: "Self-assessment is about AWARENESS, not accuracy. Students learn to notice their own gaps and develop plans.", works: "All subjects", research: "Panadero & Jonsson (2013); Nicol et al. (2014)" },
      { id: 37, title: "Feedback on Effort & Strategy (NOT Ability)", subtitle: "Frame feedback to promote growth mindset", category: "amber", categoryLabel: "Feedback", why: "Feedback focused on effort/strategy builds growth mindset. Feedback focused on ability can undermine motivation.", tryThis: "Shift language: ✗ 'You're so smart!' → ✓ 'You used a great strategy here.' ✗ 'Wrong' → ✓ 'This required a different approach.'", variation: "Effort-focused feedback, strategy-focused feedback, growth-mindset framing, challenge-oriented feedback.", insight: "Feedback messaging shapes mindset. Be intentional about reinforcing that ability develops through effort.", works: "All subjects", research: "Dweck (2006); Yeager & Dweck (2012)" },
      { id: 38, title: "Feedback Frequency & Distribution", subtitle: "More isn't always better; strategic distribution works", category: "amber", categoryLabel: "Feedback", why: "Strategic feedback moments are better than constant feedback. Spaced feedback is more effective than overwhelming students.", tryThis: "Don't grade everything. Choose high-leverage assignments (ones that check understanding of critical concepts). Provide feedback on those.", variation: "Selective feedback (high-stakes assignments only), regular but spaced feedback, formative check-ins without grades, strategic written feedback.", insight: "Teachers who grade everything often give generic feedback. Selective, high-quality feedback beats abundant generic.", works: "All subjects", research: "Hattie & Timperley (2007); Wiggins (1998)" },
      { id: 39, title: "Feedback Conversations", subtitle: "One-on-one feedback is high-impact", category: "amber", categoryLabel: "Feedback", why: "Feedback conversations (conferences) allow you to understand individual thinking and provide targeted feedback.", tryThis: "Schedule 5-minute conferences with 3–4 students. Ask: 'What do you understand? Where are you stuck? What's your strategy?'", variation: "Reading conferences, writing conferences, progress conferences, goal-setting conversations, small-group feedback sessions.", insight: "Conferences are time-intensive but high-impact. Prioritize struggling students and those ready to stretch.", works: "All subjects", research: "Fountas & Pinnell (1996); Calkins (2000)" },
      { id: 40, title: "Feedback + Error Analysis", subtitle: "Learning from mistakes through feedback", category: "amber", categoryLabel: "Feedback", why: "Analyzing WHY errors occurred deepens understanding. Feedback explaining misconceptions is more powerful than simple correction.", tryThis: "Collect common student errors. Show anonymously: 'Why do you think this happened? What's the misconception? How do we fix it?'", variation: "Error categorization, mistake analysis protocols, student self-correction, group problem-solving of common errors.", insight: "Students who analyze errors learn more than those who simply retake tests.", works: "All subjects", research: "Metcalfe (2017); Bjork & Bjork (1992)" },
      { id: 41, title: "Cognitive Load Theory - Foundational", subtitle: "Manage working memory", category: "red", categoryLabel: "Cognitive Load", why: "Working memory has limited capacity (~4 items at once). When lessons are cluttered, students cognitively overload.", tryThis: "Choose 1: Remove distracting visuals from slides • Break complex explanations into steps • Eliminate unnecessary details • Pre-teach vocabulary.", variation: "Reduce on-screen text, use worked examples, teach step-by-step, pre-teach complex concepts.", insight: "Adding MORE isn't better. Clarity, simplicity, and sequence matter more. Less is often more.", works: "All subjects", research: "Sweller (1988); Clark et al. (2005)" },
      { id: 42, title: "Reducing Extraneous Load", subtitle: "Remove distractions and unnecessary information", category: "red", categoryLabel: "Cognitive Load", why: "Extraneous load (information that doesn't contribute to learning) consumes working memory.", tryThis: "Audit materials: Remove distracting colors, unnecessary graphics, irrelevant information. Keep only what students need to learn.", variation: "Simplified slides, minimal on-screen text, focused examples, elimination of cute distractions, essential-only materials.", insight: "Students find minimalist materials easier to learn from than rich, colorful, 'engaging' ones.", works: "All subjects", research: "Sweller (1988); Clark et al. (2005)" },
      { id: 43, title: "Managing Intrinsic Load", subtitle: "Sequence complexity carefully", category: "red", categoryLabel: "Cognitive Load", why: "Intrinsic load can't be eliminated, but can be managed through sequencing from simple to complex.", tryThis: "For complex concept: Break into 2–3 smaller chunks. Teach chunk 1 fully. Then chunk 2. Then show connections. Don't present whole at once.", variation: "Chunking, part-to-whole teaching, progressive complexity, prerequisite teaching, scaffolded instruction.", insight: "Complex content isn't impossible—it's just impossible ALL AT ONCE. Sequence matters.", works: "All subjects, especially complex skills and conceptual learning", research: "Sweller (1988); Paas & van Merriënboer (2020)" },
      { id: 44, title: "Worked Examples to Reduce Load", subtitle: "Scaffolding with detailed examples", category: "red", categoryLabel: "Cognitive Load", why: "For complex learning, showing a complete worked example FIRST (with explanation) reduces cognitive load.", tryThis: "Take a complex procedure/problem. Work through step-by-step while narrating thinking. THEN have them practice.", variation: "Partially worked examples, annotated examples, video worked examples, peer-created examples, faded worked examples.", insight: "Worked examples are scaffolding. Fade them out as students gain competence.", works: "Math, sciences, writing, procedural skills", research: "Sweller (1988); Paas & van Merriënboer (2020)" },
      { id: 45, title: "Cognitive Load + Prior Knowledge", subtitle: "Build foundations to reduce future load", category: "red", categoryLabel: "Cognitive Load", why: "When students lack prior knowledge, new concepts become intrinsically harder. Building prior knowledge BEFORE new learning reduces intrinsic load.", tryThis: "Before new material: Spend time activating/building necessary background. Ask what students know. Pre-teach vocabulary if needed.", variation: "Pre-teaching, vocabulary pre-teaching, foundation-building, advance organizers, prior knowledge activation.", insight: "You can't reduce complexity of new material, but you can ensure students have the foundation to handle it.", works: "All subjects", research: "Anderson (1984); Rosenshine (1997)" },
      { id: 46, title: "Attention & Focus Management", subtitle: "Protect cognitive resources from distraction", category: "red", categoryLabel: "Cognitive Load", why: "Attention is limited and easily depleted. Reducing distractions helps students allocate attention to learning.", tryThis: "Audit classroom: Are screens visible when not needed? Competing sounds? Simplify environment for current task.", variation: "Silence notifications, minimize website tabs, reduce visual clutter, single-task windows, elimination of competing stimuli.", insight: "Load management isn't just about content complexity; it's about environmental simplicity. Protect attention.", works: "All subjects", research: "Sweller (1988); Clark et al. (2005)" },
      { id: 47, title: "Modality & Multiple Representations", subtitle: "Use words and visuals strategically", category: "red", categoryLabel: "Cognitive Load", why: "When presenting same information in multiple modalities (text AND spoken words AND images), working memory overloads.", tryThis: "Show diagram WITH NO TEXT LABELS. Explain verbally. Don't make students read AND listen AND look at once.", variation: "Audio-visual explanations, integrated diagrams with spoken narration, reduced on-screen text with vocal explanation.", insight: "More information doesn't equal better learning. Strategic, focused presentation reduces load.", works: "All subjects", research: "Sweller (1988); Paas & van Merriënboer (2020)" },
      { id: 48, title: "Elaboration: Making Meaningful Connections", subtitle: "Connect new to prior knowledge", category: "pink", categoryLabel: "Elaboration", why: "When students generate connections between new info and what they already know, they understand and remember better.", tryThis: "After presenting concept, ask: 'Why might this matter?' • 'How is this like [prior topic]?' • 'Can you give your own example?' • 'What would happen if...?'", variation: "Analogies, comparisons to prior knowledge, think-pair-share, generate-your-own-examples activities.", insight: "Elaboration is distinct from retrieval. It's the process of CONNECTING new info to existing knowledge.", works: "All subjects", research: "Craik & Lockhart (1972); Bjork & Bjork (1992)" },
      { id: 49, title: "Pre-Assessment: Know Where to Start", subtitle: "Reveal starting points, misconceptions, and gaps", category: "coral", categoryLabel: "Assessment", why: "Pre-assessing before a unit reveals what students know and what they're missing. This allows differentiation and prevents boredom or overwhelming.", tryThis: "Next unit: Spend 5 minutes on pre-assessment (quick quiz, concept map, think-pair-share, or observation). Use data to adjust pacing.", variation: "Pre-tests, concept inventories, student interviews, observation, prior knowledge activators.", insight: "Pre-assessment isn't about grading; it's about KNOWING YOUR STUDENTS so you teach smarter.", works: "All subjects, all levels", research: "Hattie & Timperley (2007); Black & Wiliam (1998)" },
      { id: 50, title: "Formative Assessment: Frequent Checks for Understanding", subtitle: "Quick, low-stakes checks during learning", category: "coral", categoryLabel: "Assessment", why: "Formative assessment reveals student understanding BEFORE grading. Teachers adjust instruction based on real-time data.", tryThis: "Pick one: Hand signals (thumbs up/down/sideways), exit tickets, quick whiteboards, 'show with fingers,' verbal check-ins. Use one today.", variation: "Daily quizzes, entrance/exit tickets, one-minute papers, polls, observation, conversations.", insight: "Formative data is for TEACHING, not grading. Use it to adjust instruction tomorrow.", works: "All subjects, all levels", research: "Black & Wiliam (1998); Hattie & Timperley (2007)" },
      { id: 51, title: "Misconception Identification: Find and Fix Wrong Thinking", subtitle: "Diagnose and explicitly address false beliefs", category: "coral", categoryLabel: "Assessment", why: "Students have robust misconceptions. Identifying and explicitly addressing them is necessary; ignoring them lets false beliefs persist.", tryThis: "Anticipate common misconceptions for upcoming lesson. Diagnose them directly. Address them explicitly and repeatedly.", variation: "Diagnostic assessments, student interviews, think-pair-share revealing misconceptions, case study analysis.", insight: "Misconceptions are sticky. Correcting them requires repeated, explicit, evidence-based intervention.", works: "All subjects, especially science and math", research: "National Research Council (2000); Kowalski (2008)" },
      { id: 52, title: "Rubrics & Clarity: Make Success Visible", subtitle: "Clear criteria and exemplars reduce anxiety", category: "coral", categoryLabel: "Assessment", why: "When students know EXACTLY what success looks like (rubric with exemplars), they hit targets better.", tryThis: "Take one assignment. Create simple rubric (3–4 criteria, 3–4 proficiency levels). Show exemplars (student work meeting each level).", variation: "Analytic rubrics, holistic rubrics, exemplar-based rubrics, student-created rubrics, performance descriptions.", insight: "Rubrics are only useful if students SEE them before starting and understand the exemplars.", works: "All subjects, especially writing, projects, presentations", research: "Wiggins (1998); Sadler (1989)" },
      { id: 53, title: "Cognitive Apprenticeship: Model, Coach, Fade", subtitle: "I do, we do, you do", category: "indigo", categoryLabel: "Skill Development", why: "Complex skills are learned by watching expert, practicing with support, then independently. The progression is research-backed.", tryThis: "Identify complex skill. Design 3 phases: I do (model), we do (guided practice), you do (independent). Build into lesson sequence.", variation: "Gradual release of responsibility, I-we-you, worked examples → guided → independent.", insight: "Scaffolding isn't permanent. Goal is INDEPENDENCE. Fade support deliberately.", works: "Complex skills (writing, analysis, problem-solving, lab work)", research: "Collins et al. (1989); Schoenfeld (1985)" },
      { id: 54, title: "Relatedness & Relevance: Connect to Student Lives and Interests", subtitle: "Why does this matter?", category: "blue", categoryLabel: "Engagement", why: "When learning connects to student interests and real-world contexts, relevance increases and motivation follows.", tryThis: "Next lesson: Explicitly name why this matters. Connect to student interests or real-world applications.", variation: "Student interest surveys, real-world problems, culturally responsive examples, current events connections, student-driven inquiries.", insight: "Relevance isn't about entertainment; it's about AUTHENTIC CONNECTION to student lives.", works: "All subjects", research: "Wiggins (1998); Ladson-Billings (1995)" },
      { id: 55, title: "Autonomy in Assignments: Give Students Choices", subtitle: "Choice increases intrinsic motivation", category: "blue", categoryLabel: "Engagement", why: "When students have choice (even small choices) in how to demonstrate learning, engagement and intrinsic motivation increase.", tryThis: "Next assignment: Offer 2–3 options for how to show learning (essay, presentation, podcast, infographic). Let students choose.", variation: "Choice boards, multiple pathways, student-selected examples, open-ended problem sets, choice in grouping.", insight: "Choice doesn't mean chaos. Offer BOUNDED choices within clear parameters.", works: "All subjects", research: "Ryan & Deci (2000); Reeve (2009)" },
      { id: 56, title: "Social Learning & Collaboration: Harness Peer Learning", subtitle: "Peers are powerful learning partners", category: "blue", categoryLabel: "Engagement", why: "Peer learning (discussing ideas, explaining to peers, collaborative problem-solving) deepens understanding and is motivating.", tryThis: "Build peer explanation into one lesson: 'Turn to neighbor and explain X.' or 'In groups, tackle this problem and explain thinking.'", variation: "Think-pair-share, cooperative learning, peer teaching, discussion protocols, jigsaw, structured discussions.", insight: "Collaboration works best with STRUCTURE (clear roles, accountability, interdependence) and PURPOSEFUL TALK.", works: "All subjects, all levels", research: "Johnson & Johnson (1989); Kagan (1994)" },
      { id: 57, title: "Intrinsic vs. Extrinsic Motivation: Foster Internal Drive", subtitle: "Meaning-making > Points and grades", category: "blue", categoryLabel: "Engagement", why: "Intrinsic motivation (doing something because it's interesting/valuable) leads to deeper learning. Extrinsic motivation can undermine intrinsic drive.", tryThis: "Examine your incentives: Are you relying on points/grades? Shift: Ask 'Why does this matter?' Design meaningful work. Reduce unnecessary rewards.", variation: "Emphasizing meaning, highlighting relevance, reducing grade-focused language, autonomy-supportive feedback, intrinsic rewards.", insight: "Intrinsic motivation is rare but buildable. Don't let extrinsic systems CROWD OUT intrinsic motivation.", works: "All subjects, all levels", research: "Ryan & Deci (2000); Kohn (1999)" }
    ];

const CATEGORY_CLASS = {
  blue: "tpd-cat-blue",
  teal: "tpd-cat-teal",
  purple: "tpd-cat-purple",
  green: "tpd-cat-green",
  amber: "tpd-cat-amber",
  red: "tpd-cat-red",
  pink: "tpd-cat-pink",
  coral: "tpd-cat-coral",
  indigo: "tpd-cat-indigo",
};

function Section({ title, text }) {
  return (
    <section className="tpd-card-section">
      <div className="tpd-card-section-title">{title}</div>
      <p className="tpd-card-section-text">{text}</p>
    </section>
  );
}

export default function TeachingPracticesDeck() {
  const [index, setIndex] = useState(0);
  const total = CARDS.length;
  const card = CARDS[index];

  // Randomize is the primary action: surface something NEW, never the same card twice in a row.
  const randomize = () => {
    if (total < 2) return;
    let nextIndex = index;
    while (nextIndex === index) {
      nextIndex = Math.floor(Math.random() * total);
    }
    setIndex(nextIndex);
  };

  const next = () => setIndex((i) => (i + 1) % total);
  const prev = () => setIndex((i) => (i - 1 + total) % total);

  return (
    <div className="tpd-root">
      <div className="tpd-header">
        <span>{total}-card teaching practices deck</span>
        <span>
          {index + 1} of {total}
        </span>
      </div>

      <div className="tpd-card-container">
        {/* key={card.id} remounts the node so the entrance animation replays on every change */}
        <article className="tpd-card" key={card.id}>
          <header className="tpd-card-header">
            <div className="tpd-card-title">
              <h3>{card.title}</h3>
              <p className="tpd-card-subtitle">{card.subtitle}</p>
            </div>
            <span className={`tpd-card-category ${CATEGORY_CLASS[card.category]}`}>
              {card.categoryLabel}
            </span>
          </header>

          <div className="tpd-card-content">
            <Section title="Why it works" text={card.why} />
            <Section title="Try this today" text={card.tryThis} />
            <Section title="Variation" text={card.variation} />
            <Section title="Research insight" text={card.insight} />
          </div>

          <footer className="tpd-card-footer">
            <div className="tpd-tag-line">
              <strong>✓ Works across:</strong> {card.works}
            </div>
            <div className="tpd-tag-line">📚 {card.research}</div>
          </footer>
        </article>
      </div>

      <div className="tpd-controls">
        <button className="tpd-randomize" onClick={randomize}>
          🎲 Randomize
        </button>
      </div>

      <div className="tpd-controls tpd-nav">
        <button onClick={prev}>← Previous</button>
        <button onClick={next}>Next →</button>
      </div>
    </div>
  );
}
